add aliases for pages
Pleesher/mediawiki-liquipedia-extension pull request #8
Opened 2017-04-06 11:48 UTC by FO-nTTaX

2017-04-06 11:49 UTC, FO-nTTaX commented
This adds and uses an alias file, avoids some php notices in more strict mediawiki setups

2017-04-07 10:50 UTC, sielver requested changes
I don't think we need the NetBeans files :)

2017-04-09 13:30 UTC, FO-nTTaX commented
changed

2017-04-09 13:59 UTC, sielver approved these changes

2017-04-09 13:59 UTC, merged